### PR TITLE
Gradio Web Demo

### PR DESCRIPTION
**Pull request by AK391**
easy to use web demo using gradio on huggingface spaces

### CODE REVIEW

**Comment by Wendison** [comment]
Hi, thank you for your work! May I know if it is possible to add new models in the future on the demo page?

**Comment by AK391** [comment]
@Wendison Hi yes it should be possible, can make a dropdown to choose between which model to load https://gradio.app/docs#i_dropdown

**Comment by Wendison** [comment]
That's great!

**Comment by Wendison** [comment]
@AK391 Hi the link of gradio web demo (https://huggingface.co/spaces/akhaliq/VQMIVC) is invalid, could you help to fix it? thx!

**Comment by AK391** [comment]
@Wendison sorry the demo was accidently set to private, it is public and also updating the sdk to the newer version of Gradio: 3.0.11 which updates the UI + other fixes

**Comment by Wendison** [comment]
@AK391 No problem, thx!

**Comment by Wendison** [comment]
@AK391 Hi, the link https://huggingface.co/spaces/akhaliq/VQMIVC is broken again, could you have a check? thx!

**Pull request merged**
